### ISSUE TITLE
Exception reported: Array index out-of-bounds

### ISSUE THREAD

**Issue by chattyaka** [kgns/gloves#16]
Fix pls

L 12/13/2019 - 00:42:20: [SM] Exception reported: Array index out-of-bounds (index 7, limit 7)
L 12/13/2019 - 00:42:20: [SM] Blaming: gloves.smx
L 12/13/2019 - 00:42:20: [SM] Call stack trace:
L 12/13/2019 - 00:42:20: [SM]   [1] Line 81, gloves/config.sp::ReadConfig
L 12/13/2019 - 00:42:20: [SM]   [2] Line 86, gloves.sp::OnConfigsExecuted

**Comment by kgns** [comment]
This was fixed along the way I guess, as I cannot replicate it
