### ISSUE TITLE
Root InGame command

### ISSUE THREAD

**Issue by ddfigueiras** [kgns/gloves#35]
It's possible to add a command for root players to remove someone's gloves? or there is any other way? Imagine if they VIP expire, it would be very helpfull to remove in-game

**Comment by crashzk** [comment]
Add cvar reset gloves of a specific player, same as for the Weapons & Knives plugin:
```
RegAdminCmd("sm_wsreset", CommandResetWeaponSkins, ADMFLAG_ROOT, "Resets weapon skins and knife of a specific player.");
```
