### ISSUE TITLE
Gloves 1.0.1

### ISSUE THREAD

**Issue by dzagu** [kgns/gloves#6]
L 01/18/2018 - 17:20:49: [SM] Exception reported: Entity 338 (338) is invalid
L 01/18/2018 - 17:20:49: [SM] Blaming: gloves.smx
L 01/18/2018 - 17:20:49: [SM] Call stack trace:
L 01/18/2018 - 17:20:49: [SM]   [0] SetEntPropEnt
L 01/18/2018 - 17:20:49: [SM]   [1] Line 108, gloves/menus.sp::ResetGlovesTimer

**Comment by distratul** [comment]
The same issue on my server too!

**Comment by paulocrash** [comment]
I noticed that my error logs have moments that show this error too:
```
L 07/16/2019 - 15:44:12: [SM] Exception reported: Entity 82 (82) is invalid
L 07/16/2019 - 15:44:12: [SM] Blaming: gloves.smx
L 07/16/2019 - 15:44:12: [SM] Call stack trace:
L 07/16/2019 - 15:44:12: [SM]   [0] SetEntPropEnt
L 07/16/2019 - 15:44:12: [SM]   [1] Line 108, gloves/menus.sp::ResetGlovesTimer
```
They are rare, but have they there, would have some solution or just waiting?

What if this affects server performance in some way?

**Comment by kgns** [comment]
try v1.0.4 out
