### ISSUE TITLE
Gloves 1.0.3 - Chat Triggers Bug

### ISSUE THREAD

**Issue by peralta00** [kgns/gloves#7]
Hi, in this version chat triggers are being shown, contrary to the [weapons](https://github.com/kaganus/weapons) plugin.

![counter-strike global offensive](https://user-images.githubusercontent.com/21270917/38314279-b75dddf0-381d-11e8-815a-93715d94cfce.jpg)

Best regards.

**Comment by kgns** [comment]
that's not a bug, it simply has not been coded in this plugin yet. keeping this open so next time i push some commits, i wont forget to add this functionality

**Comment by kgns** [comment]
added with v1.0.4
